### ISSUE TITLE
Can this library remove `bedrock-mongodb` are peerDep?

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/bedrock-ledger-consensus-uni#7]
Currently this library requires `bedrock-mongodb` as a peerDependency.
However it just uses `database.hash` which in turn calls this code:

https://github.com/digitalbazaar/bedrock-mongodb/blob/a598ac494a14c5aa753fa0dd72ccf06ceddc82f8/lib/index.js#L256-L272

Is there a common hashing function it could use from another library in it's place?

**Comment by mattcollier** [comment]
It's very important that the entire ledger stack use that exact same hashing funciton and so locking into the bedrock-mongodb version has worked well.  If we were ever to change that hashing function it would be a breaking change etc.  -1 to implementing hashing function in local code etc.

**Comment by aljones15** [comment]
That's completely fine. Closing this issue as redundant and thanks for the great answer. My point was not to use local code, but to use a shared module.
